# Student Data

## Data

In [3]:
data =[123,124123,12,312,3,124,5,43,6,6,8575,341] 

print(data)
print(data * 2)

[123, 124123, 12, 312, 3, 124, 5, 43, 6, 6, 8575, 341]
[123, 124123, 12, 312, 3, 124, 5, 43, 6, 6, 8575, 341, 123, 124123, 12, 312, 3, 124, 5, 43, 6, 6, 8575, 341]


In [10]:
import numpy as np

grades = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(grades)
print(grades * 2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [11]:
grades.shape

grades[3]

grades.mean()

np.float64(5.5)

In [12]:
study_hours = [10.0, 20.2, 30.5, 40.1, 50.7, 60.5, 70.9, 3.60, 91.2, 10.34]

student_data = np.array([study_hours, grades])

In [14]:
student_data[1]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
avg_study = student_data[0].mean()
avg_grade = student_data[1].mean()

print(f'average study time: {avg_study}')
print(f'average of grades: {avg_grade}')

average study time: 38.803999999999995
average of grades: 5.5


## Working With DataFrames

In [51]:
import pandas as pd 

df_students = pd.DataFrame({
    'Name': ['john', 'jane', 'doe', 'joe', 'joseph', 'josh', 'joshua', 'joshie', 'isaac', 'chris'],
    'Age': [23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
    'StudyHours': [10.0, 20.2, 30.5, 40.1, 50.7, 60.5, 70.9, 3.60, 91.2, 10.34],
    'Grade': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
})
df_students

Name  Age  StudyHours  Grade
0    john   23       10.00      1
1    jane   24       20.20      2
2     doe   25       30.50      3
3     joe   26       40.10      4
4  joseph   27       50.70      5
5    josh   28       60.50      6
6  joshua   29       70.90      7
7  joshie   30        3.60      8
8   isaac   31       91.20      9
9   chris   32       10.34     10

In [53]:
df_students.loc[1]

df_students.loc[1, 'Grade']

df_students[df_students['Name'] == 'jane']

df_students.query('Name == "doe"')

df_students[df_students.Grade > 6]

Name  Age  StudyHours  Grade
6  joshua   29       70.90      7
7  joshie   30        3.60      8
8   isaac   31       91.20      9
9   chris   32       10.34     10

## Working With CSV Files and Process CSV Datas

In [ ]:
%pip install wget

import wget
url = 'https://raw.githubusercontent.com/MicrosoftDocs/mslearn-introduction-to-machine-learning/main/Data/ml-basics/grades.csv'
wget.download(url, 'grades.csv')

df_students = pd.read_csv('grades.csv', delimiter=',', header='infer')

In [72]:
df_students

df_students.isnull().sum()

Name          0
StudyHours    0
Grade         0
dtype: int64

In [68]:
df_students.StudyHours = df_students.StudyHours.fillna(df_students.StudyHours.mean())

In [71]:
df_students = df_students.dropna(axis=0)


In [74]:
mean_study = df_students.StudyHours.mean()

mean_grade = df_students.Grade.mean()

print(f'average grade: {mean_grade}')
print(f'average study time: {mean_study}')

average grade: 49.18181818181818
average study time: 10.522727272727273


In [79]:
df_students[df_students.Grade > mean_grade]
df_students[df_students.Grade > mean_grade].Grade.mean()

np.float64(65.18181818181819)

In [ ]:
passed = pd.Series(df_students.Grade > 60)
df_students = pd.concat([df_students, passed.rename('Passed')], axis=1)

df_students

In [91]:
df_students.groupby(df_students.Passed)['StudyHours'].mean()

Passed
False     8.783333
True     14.250000
Name: StudyHours, dtype: float64

In [ ]:
df_students.groupby(df_students.Passed).Name.count()

In [95]:
df_students = df_students.sort_values('Grade', ascending=False)

df_students

Name  StudyHours  Grade  Passed
3       Rosie       16.00   97.0    True
10  Francesca       15.50   82.0    True
9    Giovanni       14.50   74.0    True
14      Jenny       15.50   70.0    True
21      Aisha       12.00   64.0    True
20     Daniel       12.50   63.0    True
11      Rajab       13.75   62.0    True
6    Frederic       11.50   53.0   False
19       Skye       12.00   52.0   False
0         Dan       10.00   50.0   False
1       Joann       11.50   50.0   False
4       Ethan        9.25   49.0   False
18      Anila       10.00   48.0   False
2       Pedro        9.00   47.0   False
7      Jimmie        9.00   42.0   False
12    Naiyana        9.00   37.0   False
16     Helena        9.00   36.0   False
17      Ismat        6.00   35.0   False
15     Jakeem        8.00   27.0   False
8      Rhonda        8.50   26.0   False
13       Kian        8.00   15.0   False
5       Vicky        1.00    3.0   False