Student Datas

In [3]:
data =[123,124123,12,312,3,124,5,43,6,6,8575,341] 

print(data)
print(data * 2)

[123, 124123, 12, 312, 3, 124, 5, 43, 6, 6, 8575, 341]
[123, 124123, 12, 312, 3, 124, 5, 43, 6, 6, 8575, 341, 123, 124123, 12, 312, 3, 124, 5, 43, 6, 6, 8575, 341]


In [10]:
import numpy as np

grades = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(grades)
print(grades * 2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [11]:
grades.shape

grades[3]

grades.mean()

np.float64(5.5)

In [12]:
study_hours = [10.0, 20.2, 30.5, 40.1, 50.7, 60.5, 70.9, 3.60, 91.2, 10.34]

student_data = np.array([study_hours, grades])

In [14]:
student_data[1]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
avg_study = student_data[0].mean()
avg_grade = student_data[1].mean()

print(f'average study time: {avg_study}')
print(f'average of grades: {avg_grade}')

average study time: 38.803999999999995
average of grades: 5.5
